---
title: 'PHASE FOUR: GRAPHS AND FIGURES'
author: "Chris Low"
date: "13/09/2021"
output: html_document
---

```{r load packages, echo=TRUE}

library(ggplot2) # graphical visualization
library(dplyr) # data manipulations
library(viridis) # 
library(hrbrthemes) # colour themes
library(sjPlot) # creating tables
library(gridExtra) # sort out gridding for plots
library(ggthemes) # make nice themed plots
library(RColorBrewer) # make colour palletes
library(scales) # changing metric scales

```
# Create plotting themes
```{r plotting theme, echo=TRUE}

theme_Publication <- function(base_size=14, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}


```


# Load dataset
```{r load data, echo=TRUE}

# Just save priority EDGE lineage list and PD_mammal_merged list as essential for analysis: mammals_pd_merged, EDGE_priority_lineages, ePD_priority_lineages (final datasets so far!!)
load("C:/Users/Student/Zoological Society of London/EDGEofExistence - Chris Low - EDGE lineages/Project II/Data and analysis/EDGE_families_and_scores/EDGE_LINEAGES_FOR_ANALYSIS.RData")

```

## Creating a density plot to explore DD of species across taxonomic groups
```{r DD/NE, include=FALSE}

# load in packages
DD_NE_density <- read.csv(file = "C:/Users/Student/Zoological Society of London/EDGEofExistence - Chris Low - EDGE lineages/Project II/Data and analysis/EDGE_families_and_scores/taxonomic_summary.csv")

DD_NE_density$percent <- DD_NE_density$no_DD_NE_prop*100

# plot histogram of DD/ NE distribution for all my taxonomic groups- data must be long format

tiff("C:/Users/Student/Zoological Society of London/EDGEofExistence - Chris Low - EDGE lineages/Project II/Results/Conservation status/DD_ALL_taxonomic_groups.tiff", units = "in", width = 7, height = 5, res = 300)

ggplot(DD_NE_density, aes(no_DD_NE_prop, fill = Taxonomic_group)) + 
  geom_histogram(aes(y = stat(density) * 0.1), binwidth = 0.1, color = "black", alpha=0.9) + 
  scale_y_continuous(labels = percent ) +
  facet_wrap(~ Taxonomic_group, ncol = 2, nrow = 2) +
  scale_fill_manual(values = my.pal, labels = c("Amphibians", "Birds", "Mammals", "Reptiles")) +
  labs(x = "Proportion of family with DD or NE species", y = "% of family") +
  theme(axis.text = element_text(face = "bold"),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.title.y = element_text(size = 12, hjust = 0.5, face = "bold"),
        axis.title.x = element_text(size = 12, hjust = 0.5, face = "bold"),
        strip.text.x = element_text(size = 0), # remove taxonomic group listings- use images instead
        panel.spacing = unit(1, "lines")) + # space between each plot
  scale_fill_brewer(palette = "Accent", name = "Taxonomic group") +
  #scale_fill_discrete(name = "Taxonomic group") +
  theme_Publication()

dev.off()



```

# Fig 1 Bar graph of ePD loss for IUCN families with all threatened species 

```{r IUCN red list family, echo=TRUE}

# subset famileis which entire population are threatened with extinction
families_threatened <- mammals_pd_merged[which(mammals_pd_merged$assessed_threat_prop == 1),]

# select important columns
families_threatened <- families_threatened[,c(1:3,7,9,14,39)]

# subset families that have all been assessed
families_threatened <- families_threatened[which(families_threatened$unassessed_prop == 0),]

# round up whole numbers
families_threatened$median_EDGE <- round(families_threatened$median_EDGE, digits = 2)

# label number of species and how threatened the lineage is
families_threatened$Group[families_threatened$richness == 1] <- "Monotypic"
families_threatened$Group[families_threatened$richness %in% 2:10] <- "< 10 spp"
families_threatened$Group[families_threatened$richness > 10] <- "> 10 spp"

# Reorder df 
families_threatened <- transform(families_threatened,
          Family = reorder(Family,order(median_EDGE, decreasing = FALSE))) 

tiff("C:/Users/Student/Zoological Society of London/EDGEofExistence - Chris Low - EDGE lineages/Project II/Results/ePD loss and EDGE lineage framework/all_families_threatened.tiff", units = "in", width = 6, height = 5, res = 300)

# plot number of families with all species threatened with extinction
p <- ggplot(data = families_threatened, aes(x = Family, y = median_EDGE, fill = Group)) +
  geom_bar(position = position_dodge(width = 2), width = 0.7, stat = 'identity') +
  coord_flip() + # flip axis on it's side
  scale_fill_manual(values = c("orange", "yellow", "red")) +
   labs(x = "Family", y = "Median EDGE score") + # change axis titles
  theme_Publication()

dev.off()



```

# Creating a bar chart of the top 10% of ePD loss families

```{r top ePD loss, echo=TRUE}

# subset ePD loss data
ePD_loss_df <- mammals_pd_merged[,c(2:3, 14:18)]

# order df by ePD loss scores
ePD_loss_df <- ePD_loss_df[order(ePD_loss_df$Median.exPD, decreasing = TRUE),]

# subset top 10% of ePD loss
ePD_loss_df <- ePD_loss_df[c(1:10),]

# round up whole numbers
ePD_loss_df$Median.exPD <- round(ePD_loss_df$Median.exPD, digits = 0)
ePD_loss_df$Lwr.Quantile <- round(ePD_loss_df$Lwr.Quantile, digits = 0)
ePD_loss_df$Uppr.Quantile <- round(ePD_loss_df$Uppr.Quantile, digits = 0)

# Reorder df 
ePD_loss_df <- transform(ePD_loss_df,
          Family = reorder(Family,order(Median.exPD, decreasing = FALSE))) 

# write out file
tiff("C:/Users/Student/Zoological Society of London/EDGEofExistence - Chris Low - EDGE lineages/Project II/Results/ePD loss and EDGE lineage framework/top_10_ePD_loss_families.tiff", units = "in", width = 7, height = 5, res = 300)

# Create ggplot
p <- ggplot(data = ePD_loss_df, aes(x = Family, y = Median.exPD, label = richness))+
  geom_bar(position = position_dodge(width = 2), width = 0.7, fill = "gray", color = "black", stat = 'identity') +
  geom_text(aes(label = richness), # add species richness as text
            vjust = 0.4,
            hjust = -0.5,
            size =4) +
  coord_flip() + # flip axis on it's side
  labs(x = "Family", y = "Median ePD loss (*species richness)") + # change axis titles
  theme_Publication()

dev.off()

```


# Create table of EDGE prioirty lineages

```{r EDGE lineage table, echo=TRUE}

# Get subset of EDGE prioirty lineages
EDGE_prioirty <- subset(mammals_pd_merged, priority_type == "Priority lineage")

# subset column needed for table
EDGE_prioirty_table <- EDGE_prioirty[,c(1:3,39,49,14)]

# rename columns
names(EDGE_prioirty_table)[3] <- "No. of species in family"
names(EDGE_prioirty_table)[4] <- "Median EDGE score"
names(EDGE_prioirty_table)[5] <- "Median ED (MY)"
names(EDGE_prioirty_table)[6] <- "Median ePD loss (MY)"

# Order EDGE score
EDGE_prioirty_table <- EDGE_prioirty_table[order(EDGE_prioirty_table$`Median EDGE score`, decreasing = TRUE),]

# Create table into word doc 
tab_df(EDGE_prioirty_table,
       alternate.rows = TRUE,
       digits = 2,
       col.header = NULL,
       file = "EDGE_priority_lineages.doc")

# EDGE prioirty list full
EDGE_prioirty_table_full <- EDGE_priority_lineages[,c(2,3,41,39,49)]

# Order EDGE score
EDGE_prioirty_table_full <- EDGE_prioirty_table_full[order(EDGE_prioirty_table_full$median_EDGE, decreasing = TRUE),]

# rename columns
names(EDGE_prioirty_table_full)[2] <- "No. of species in family"
names(EDGE_prioirty_table_full)[3] <- "Priority type"
names(EDGE_prioirty_table_full)[4] <- "Median EDGE score"
names(EDGE_prioirty_table_full)[5] <- "Median ED (MY)"

# Create table into word doc 
tab_df(EDGE_prioirty_table_full,
       alternate.rows = TRUE,
       digits = 2,
       col.header = NULL,
       file = "EDGE_priority_lineages_full.doc")

webshot("EDGE_priority_lineages.html", "EDGE_priority_lineages.png")

```

```{r threat heat map, echo=TRUE}

# subset data


```
